name: .NET on Windows

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: List directory contents (for debugging)
      run: ls -R  # This will list all files and directories recursively

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore dotStocks.sln  # Correct relative path to .sln file

    - name: Build
      run: dotnet build dotStocks.sln --no-restore

    - name: Test
      run: dotnet test dotStocks.sln --no-build --verbosity normal
